fantasy_url: https://nba.udn.com/fantasy/

injuries_url: https://www.cbssports.com/nba/injuries/

espn_url: https://www.espn.com/nba/schedule/_/date/

number_five_url: https://www.numberfire.com/nba/daily-fantasy/daily-basketball-projections#_=_

# Number_Five, or Average
mode: Average
# Mode Average should set the n.
last_n_games: 12
