fantasy_url: https://nba.udn.com/fantasy/

injuries_url: https://www.cbssports.com/nba/injuries/

espn_url: https://www.espn.com/nba/schedule/_/date/

# Fantasy_Projections or Averge
mode: Averge
last_n_games: 5