fantasy_url: https://nba.udn.com/fantasy/

injuries_url: https://www.cbssports.com/nba/injuries/

espn_url: https://www.espn.com/nba/schedule/_/date/

# FAN_DUEL, Draft_Kings, or Averge
mode: Draft_Kings
last_n_games: 3